name: Build and release for all platforms

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check_version:
    name: Check version
    uses: ./.github/workflows/check-version-tag.yml
  fetch:
    needs: [check_version]
    if: ${{ needs.check_version.outputs.should_run != 'false' }}
    name: Fetch
    uses: ./.github/workflows/fetch.yml
    with:
      runner_label: macro-linux
  build_release:
    needs: [check_version, fetch]
    if: ${{ needs.check_version.outputs.should_run != 'false' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x64
            os: macro-windows
            runner: WINDOWS_RUNNER_INSTANCE_ID
            working_dir: el
          - name: Linux x64
            os: macro-linux
            runner: LINUX_RUNNER_INSTANCE_ID
            working_dir: el
    name: Build for ${{ matrix.name }}
    uses: ./.github/workflows/build.yml
    with:
      runner_label: ${{ matrix.os }}
      working_dir: ${{ matrix.working_dir }}
      version: ${{ needs.check_version.outputs.version }}
  build_release_mac:
    name: Build for Mac ${{ matrix.name }}
    if: ${{ needs.check_version.outputs.should_run != 'false' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # - name: x86_64
          #   runner: macro-x641
          - name: arm64
            runner: macro-arm1
    needs: [check_version]
    uses: ./.github/workflows/build_mac.yml
    with:
      version: ${{ needs.check_version.outputs.version }}
      runner_label: ${{ matrix.runner }}
  generate_sha:
    name: Generate SHA
    needs: [check_version, build_release, build_release_mac]
    uses: ./.github/workflows/generate-sha.yml
    with:
      version: ${{ needs.check_version.outputs.version }}
  publish:
    name: Publish Electron to NPM Registry
    needs: [check_version, generate_sha]
    uses: ./.github/workflows/publish.yml
    with:
      version: ${{ needs.check_version.outputs.version }}
    secrets:
      NPM_AUTH: ${{ secrets.NPM_AUTH }}
